markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Bobby Norton
production_url : http://www.bobbynorton.com
description: "Better atoms through bits..."
disqus_shortname: bobbyno
analytics: UA-
gauges: 512adf7d108d7b29e70000a3
author :
  name : Bobby Norton
  github : bobbyno
  twitter : bobbynorton
  linkedin : bobbynorton
